[workspace]
resolver = "2"
members = [
    "crates/abyss-core",
    "crates/abyss-interpreter",
    "crates/abyss-cli",
    "crates/abyss-wasm",
]

[workspace.package]
version = "0.5.0"
edition = "2024"
authors = ["liebe-magi <ripe.gold1058@fastmail.com>"]
license = "MIT"
repository = "https://github.com/liebe-magi/abyss-lang"
homepage = "https://abyss-lang.dev"

[workspace.dependencies]
abyss-core = { path = "crates/abyss-core", version = "0.5.0" }
abyss-interpreter = { path = "crates/abyss-interpreter", version = "0.5.0" }
ariadne = "0.6"
chumsky = "0.13"
ordered-float = "5"

[workspace.metadata.release]
shared-version = true
tag = false
push = false
publish = false
